# Generated by Django 4.1.2 on 2022-11-02 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_image', models.ImageField(blank=True, help_text='Add contact image/s', null=True, upload_to='')),
                ('contact_shieeetnigga', models.TextField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Realestate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_addet', models.DateField(blank=True, null=True)),
                ('date_when_aviable', models.TimeField(blank=True, null=True)),
                ('realestate_image', models.ImageField(blank=True, help_text='Add realestate images', null=True, upload_to='')),
                ('price', models.IntegerField(blank=True, help_text='What is the PRICE?', null=True)),
                ('area', models.IntegerField(blank=True, help_text='Square meters?', null=True)),
                ('location', models.CharField(blank=True, help_text='What is realestate address?', max_length=100, null=True)),
                ('ownership', models.CharField(blank=True, choices=[('Brak', 'Brak'), ('Własność', 'Własność'), ('Spółdzielcze własnościowe prawo', 'Spółdzielcze własnościowe prawo'), ('Udział', 'Udział'), ('Spółdzielcze lokatorskie prawo', 'Spółdzielcze lokatorskie prawo'), ('Inne', 'Inne')], help_text='What type of ownership law?', max_length=40, null=True)),
                ('area_land', models.IntegerField(blank=True, help_text='What is the land area?', null=True)),
                ('land_shape', models.CharField(blank=True, choices=[('Brak', 'Brak'), ('Nieregularny', 'Nieregularny'), ('Kwadrat', 'Kwadrat'), ('Prostokąt', 'Prostokąt'), ('Trapez', 'Trapez'), ('Trójkąt', 'Trójkąt'), ('Inne', 'Inne')], help_text='What shape is the land?', max_length=13, null=True)),
                ('drive', models.CharField(blank=True, choices=[('Brak', 'Brak'), ('Asfaltowy', 'Asfaltowy'), ('Utwardzany', 'Utwardzany'), ('Kostka brukowa', 'Kostka brukowa'), ('inny', 'inny')], help_text='What type of drive?', max_length=15, null=True)),
                ('rooms', models.IntegerField(blank=True, help_text='How many rooms?', null=True)),
                ('floor', models.IntegerField(blank=True, help_text='What floor is it?', null=True)),
                ('floors', models.IntegerField(blank=True, help_text='How many floors the building has?', null=True)),
                ('market', models.CharField(blank=True, choices=[('Wtórny', 'Wtórny'), ('Pierwotny', 'Pierwotny')], help_text='What type of market?', max_length=10, null=True)),
                ('building_material', models.CharField(blank=True, choices=[('Brak', 'Brak'), ('Cegła', 'Cegła'), ('Pustak', 'Pustak'), ('Ytong', 'Ytong'), ('Beton', 'Beton'), ('Inny', 'Inny')], help_text='What was used to build?', max_length=8, null=True)),
                ('roof', models.CharField(blank=True, choices=[('Brak', 'Brak'), ('Płaski', 'Płaski'), ('Jednospadowy', 'Jednospadowy'), ('Dwuspadowy', 'Dwuspadowy'), ('Wielospadowy', 'Wielospadowy'), ('Inny', 'Inny')], help_text='What type of roof?', max_length=14, null=True)),
                ('roof_material', models.CharField(blank=True, choices=[('Brak', 'Brak'), ('Papa', 'Papa'), ('Dachówka', 'Dachówka'), ('Blacha', 'Blacha'), ('Inny', 'Inny')], help_text='The roof is made of?', max_length=10, null=True)),
                ('media', models.CharField(blank=True, choices=[('1', 'TAK'), ('2', 'NIE')], help_text='Are media available?', max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RealestateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_data', models.TextField(help_text='Please leave Your Name and Phone Number, we will call you within 24h', max_length=100)),
                ('name', models.CharField(blank=True, choices=[('Apartament', 'Apartament'), ('Mieszkanie', 'Mieszkanie'), ('Dom', 'Dom'), ('Działka', 'Działka'), ('Lokale', 'Lokale'), ('Obiekty', 'Obiekty'), ('Inny', 'Inny')], help_text='What type is the realestate?', max_length=12, null=True)),
                ('condition', models.CharField(blank=True, choices=[('Zrobione Pod Klucz', 'Zrobione Pod Klucz'), ('Do remontu', 'Do remontu'), ('Do odświeżenia', 'Do odświeżenia'), ('Stan deweloperski', 'Stan deweloperski'), ('Działka budowlana', 'Działka budowlana'), ('Działka leśna', 'Działka leśna'), ('Działka rolna', 'Działka rolna'), ('Inny', 'Inny')], help_text='What is the realestate condition?', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realtor_image', models.ImageField(blank=True, help_text='Add realestate images', null=True, upload_to='')),
                ('bio', models.TextField(default='', max_length=250)),
                ('title', models.CharField(blank=True, choices=[('Asystent/ka Biura', 'Asystent/ka Biura'), ('Młodszy Doradca ds. Nieruchomości', 'Młodszy Doradca ds. Nieruchomości'), ('Doradca ds. Nieruchomości', 'Doradca ds. Nieruchomości'), ('Starszy Doradca ds. Nieruchomości', 'Starszy Doradca ds. Nieruchomości')], help_text='What position in the company?', max_length=35, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
